<?php
$is_division = in_array($this->session->position, array('division', 'division_head'), true);
$scope = $is_division ? array('type' => 'division', 'id' => (int) $this->session->division) : array('type' => 'region', 'id' => (int) $this->session->region);
$summary = $this->Page_model->learning_gap_summary($scope);
$division_rows = !$is_division ? $this->Page_model->learning_gap_division_summary((int) $this->session->region) : array();
$records_url = base_url('Pages/learning_gap_records');
$overview_url = base_url('Pages/learning_gap');
$display_name = isset($this->session->user) && trim((string) $this->session->user) !== '' ? mb_convert_case((string) $this->session->user, MB_CASE_TITLE, 'UTF-8') : ($is_division ? 'Division User' : 'Regional User');
$record_count = (int) $summary->record_count;
$school_count = (int) $summary->school_count;
$learners_assessed = (int) $summary->learners_assessed;
$learners_with_gap = (int) $summary->learners_with_gap;
$gap_rate = $learners_assessed > 0 ? ($learners_with_gap / $learners_assessed) * 100 : 0;
$active_division_count = 0;
foreach ($division_rows as $division_row) { if ((int) $division_row->record_count > 0) { $active_division_count++; } }
$division_count = count($division_rows);
$reporting_rate = $division_count > 0 ? ($active_division_count / $division_count) * 100 : 0;
$priority_rows = array_slice(array_filter($division_rows, function ($row) { return (int) $row->record_count > 0; }), 0, 3);
?>
<style>
    .scope-lg { --navy:#123f63; --blue:#217dac; --sky:#eaf6fb; --line:#dce8ef; --ink:#243447; --muted:#6d7e8e; --amber:#c98616; --green:#21815c; }
    .scope-lg .lg-hero { position:relative; overflow:hidden; display:flex; justify-content:space-between; align-items:center; gap:24px; margin:18px 0 22px; padding:31px; border-radius:18px; color:#fff; background:linear-gradient(125deg,var(--navy),var(--blue)); box-shadow:0 14px 30px rgba(18,63,99,.18); }
    .scope-lg .lg-hero:after { content:''; position:absolute; width:250px; height:250px; right:-75px; bottom:-155px; border:34px solid rgba(255,255,255,.12); border-radius:50%; }
    .scope-lg .lg-hero-copy, .scope-lg .lg-hero-actions { position:relative; z-index:1; }
    .scope-lg .lg-eyebrow { display:block; margin-bottom:7px; color:#c9eafa; font-size:11px; font-weight:700; letter-spacing:.1em; text-transform:uppercase; }
    .scope-lg .lg-hero h1 { margin:0 0 7px; color:#fff; font-size:28px; font-weight:700; }.scope-lg .lg-hero p { max-width:700px; margin:0; color:#dceefa; }
    .scope-lg .lg-hero-actions { display:flex; flex-wrap:wrap; gap:9px; }.scope-lg .lg-hero .btn { border-radius:999px; font-weight:700; white-space:nowrap; }.scope-lg .lg-hero .btn-outline-light { border-color:rgba(255,255,255,.65); }
    .scope-lg .lg-stat-link { display:block; height:calc(100% - 20px); margin-bottom:20px; color:inherit; text-decoration:none; }.scope-lg .lg-stat { height:100%; padding:19px; border:1px solid var(--line); border-radius:14px; background:#fff; box-shadow:0 6px 19px rgba(18,63,99,.06); transition:transform .18s ease,box-shadow .18s ease; }.scope-lg .lg-stat-link:hover .lg-stat { transform:translateY(-3px); box-shadow:0 12px 25px rgba(18,63,99,.12); }
    .scope-lg .lg-stat-top { display:flex; align-items:center; justify-content:space-between; gap:12px; }.scope-lg .lg-stat-icon { display:inline-flex; align-items:center; justify-content:center; width:43px; height:43px; border-radius:12px; color:var(--blue); background:var(--sky); font-size:21px; }.scope-lg .lg-stat small { display:block; margin-top:13px; color:var(--muted); font-size:11px; font-weight:700; letter-spacing:.06em; text-transform:uppercase; }.scope-lg .lg-stat strong { display:block; margin-top:4px; color:var(--navy); font-size:27px; line-height:1.1; }.scope-lg .lg-stat-hint { display:block; margin-top:10px; color:var(--blue); font-size:12px; font-weight:600; }
    .scope-lg .lg-card { height:calc(100% - 22px); margin-bottom:22px; border:1px solid var(--line); border-radius:15px; background:#fff; box-shadow:0 6px 19px rgba(18,63,99,.06); overflow:hidden; }.scope-lg .lg-card-head { display:flex; align-items:flex-start; justify-content:space-between; gap:15px; padding:20px 22px; border-bottom:1px solid var(--line); background:#fbfdfe; }.scope-lg .lg-card-head h4 { margin:0 0 4px; color:var(--navy); font-size:16px; font-weight:700; }.scope-lg .lg-card-head p,.scope-lg .lg-card-head small { margin:0; color:var(--muted); font-size:12px; }.scope-lg .lg-card-body { padding:20px 22px; }
    .scope-lg .coverage-number { color:var(--navy); font-size:28px; font-weight:700; line-height:1; }.scope-lg .coverage-label { margin:7px 0 13px; color:var(--muted); font-size:12px; }.scope-lg .lg-progress { height:9px; border-radius:999px; background:#e9f0f4; overflow:hidden; }.scope-lg .lg-progress span { display:block; height:100%; border-radius:inherit; background:linear-gradient(90deg,#1d709e,#3fa8d0); }.scope-lg .coverage-foot { display:flex; justify-content:space-between; gap:10px; margin-top:10px; color:var(--muted); font-size:12px; }
    .scope-lg .priority-list { list-style:none; margin:0; padding:0; }.scope-lg .priority-list li { display:flex; align-items:center; gap:12px; padding:12px 0; border-bottom:1px solid #edf2f5; }.scope-lg .priority-list li:first-child { padding-top:0; }.scope-lg .priority-list li:last-child { padding-bottom:0; border-bottom:0; }.scope-lg .priority-rank { display:inline-flex; align-items:center; justify-content:center; flex:0 0 28px; width:28px; height:28px; border-radius:50%; color:#9b6410; background:#fff2d9; font-size:12px; font-weight:700; }.scope-lg .priority-name { flex:1; min-width:0; color:var(--ink); font-size:13px; font-weight:700; }.scope-lg .priority-name a { color:inherit; }.scope-lg .priority-name small { display:block; overflow:hidden; color:var(--muted); font-size:11px; font-weight:400; text-overflow:ellipsis; white-space:nowrap; }.scope-lg .priority-count { color:var(--amber); font-size:14px; font-weight:700; text-align:right; }.scope-lg .priority-count small { display:block; color:var(--muted); font-size:10px; font-weight:400; }
    .scope-lg .summary-table { min-width:780px; margin:0; }.scope-lg .summary-table th { padding:12px 15px; border-top:0; color:var(--muted); font-size:10px; letter-spacing:.05em; text-transform:uppercase; white-space:nowrap; }.scope-lg .summary-table td { padding:14px 15px; vertical-align:middle; color:#435467; }.scope-lg .summary-table tbody tr:hover { background:#f8fcfe; }.scope-lg .summary-table a { color:var(--blue); font-weight:700; text-decoration:none; }.scope-lg .summary-table a:hover { text-decoration:underline; }.scope-lg .status-pill { display:inline-block; padding:4px 8px; border-radius:999px; color:var(--green); background:#e9f7f0; font-size:10px; font-weight:700; }.scope-lg .status-pill.muted { color:#788692; background:#f0f3f5; }.scope-lg .empty-state { padding:25px; color:var(--muted); text-align:center; }
    @media (max-width:767.98px) { .scope-lg .lg-hero { align-items:flex-start; flex-direction:column; padding:24px; }.scope-lg .lg-hero-actions,.scope-lg .lg-hero .btn { width:100%; }.scope-lg .lg-card-head { padding:18px; }.scope-lg .lg-card-body { padding:18px; } }
</style>
<div class="scope-lg">
    <section class="lg-hero"><div class="lg-hero-copy"><span class="lg-eyebrow">Least Learned Competencies Monitoring</span><h1><?= $is_division ? 'Division Learning Gap Summary' : 'Regional Learning Gap Overview'; ?></h1><p><?= $is_division ? 'Track submitted assessment results and learning needs across your division.' : 'Welcome, ' . html_escape($display_name) . '. Monitor reporting coverage and the learning needs emerging across every division.'; ?></p></div><div class="lg-hero-actions"><a class="btn btn-light" href="<?= $overview_url; ?>"><i class="mdi mdi-chart-bar mr-1"></i> Learning Gap Summary</a><a class="btn btn-outline-light" href="<?= $records_url; ?>"><i class="mdi mdi-format-list-bulleted mr-1"></i> View Records</a></div></section>
    <div class="row">
        <div class="col-sm-6 col-xl-3"><a class="lg-stat-link" href="<?= $records_url; ?>"><div class="lg-stat"><div class="lg-stat-top"><span>Reporting schools</span><span class="lg-stat-icon"><i class="mdi mdi-school-outline"></i></span></div><small>Schools with submissions</small><strong><?= number_format($school_count); ?></strong><span class="lg-stat-hint">Review submitted records <i class="mdi mdi-arrow-right"></i></span></div></a></div>
        <div class="col-sm-6 col-xl-3"><a class="lg-stat-link" href="<?= $records_url; ?>"><div class="lg-stat"><div class="lg-stat-top"><span>Encoded records</span><span class="lg-stat-icon"><i class="mdi mdi-file-document-outline"></i></span></div><small>Competency gap entries</small><strong><?= number_format($record_count); ?></strong><span class="lg-stat-hint">View all entries <i class="mdi mdi-arrow-right"></i></span></div></a></div>
        <div class="col-sm-6 col-xl-3"><a class="lg-stat-link" href="<?= $records_url; ?>"><div class="lg-stat"><div class="lg-stat-top"><span>Learners assessed</span><span class="lg-stat-icon"><i class="mdi mdi-account-group-outline"></i></span></div><small>Unique grade-level totals</small><strong><?= number_format($learners_assessed); ?></strong><span class="lg-stat-hint">Open source data <i class="mdi mdi-arrow-right"></i></span></div></a></div>
        <div class="col-sm-6 col-xl-3"><a class="lg-stat-link" href="<?= $records_url; ?>"><div class="lg-stat"><div class="lg-stat-top"><span>Learners with gap</span><span class="lg-stat-icon"><i class="mdi mdi-alert-circle-outline"></i></span></div><small><?= number_format($gap_rate, 1); ?>% of assessed learners</small><strong><?= number_format($learners_with_gap); ?></strong><span class="lg-stat-hint">Identify priority support <i class="mdi mdi-arrow-right"></i></span></div></a></div>
    </div>
    <?php if (!$is_division) : ?><div class="row"><div class="col-lg-5"><section class="lg-card"><div class="lg-card-head"><div><h4>Division reporting coverage</h4><p>Divisions with at least one submitted learning-gap record.</p></div><small><?= $active_division_count; ?> / <?= $division_count; ?></small></div><div class="lg-card-body"><div class="coverage-number"><?= number_format($reporting_rate, 1); ?>%</div><p class="coverage-label">of divisions are represented in the regional overview</p><div class="lg-progress"><span style="width:<?= min(100, max(0, $reporting_rate)); ?>%"></span></div><div class="coverage-foot"><span><?= $active_division_count; ?> reporting divisions</span><span><?= max(0, $division_count - $active_division_count); ?> without records</span></div></div></section></div><div class="col-lg-7"><section class="lg-card"><div class="lg-card-head"><div><h4>Priority attention</h4><p>Divisions with the highest recorded number of learners with gaps.</p></div><a href="<?= $records_url; ?>">View records</a></div><div class="lg-card-body"><?php if (empty($priority_rows)) : ?><div class="empty-state">No division has submitted learning-gap data yet.</div><?php else : ?><ol class="priority-list"><?php foreach ($priority_rows as $index => $row) : $row_url = $records_url . '?division_id=' . (int) $row->division_id; ?><li><span class="priority-rank"><?= $index + 1; ?></span><div class="priority-name"><a href="<?= $row_url; ?>"><?= html_escape($row->division_name); ?></a><small><?= number_format((int) $row->school_count); ?> reporting school<?= (int) $row->school_count === 1 ? '' : 's'; ?> · <?= number_format((int) $row->record_count); ?> records</small></div><div class="priority-count"><?= number_format((int) $row->learners_with_gap); ?><small>learners with gap</small></div></li><?php endforeach; ?></ol><?php endif; ?></div></section></div></div>
        <section class="lg-card"><div class="lg-card-head"><div><h4>Regional performance by division</h4><p>Use the linked figures to open the submitted records for a division.</p></div><small><?= number_format($division_count); ?> divisions</small></div><div class="table-responsive"><table class="table summary-table mb-0"><thead><tr><th>Division</th><th>Reporting status</th><th>School submissions</th><th>Submission rate</th><th>Records</th><th>Learners assessed</th><th>Learners with gap</th><th>Gap rate</th></tr></thead><tbody><?php if (empty($division_rows)) : ?><tr><td colspan="8" class="empty-state">No divisions are configured for this regional account.</td></tr><?php else : foreach ($division_rows as $row) : $record_link = $records_url . '?division_id=' . (int) $row->division_id; $row_assessed = (int) $row->learners_assessed; $row_gap_rate = $row_assessed > 0 ? ((int) $row->learners_with_gap / $row_assessed) * 100 : 0; $row_school_total = (int) $row->total_school_count; $row_submission_rate = $row_school_total > 0 ? ((int) $row->school_count / $row_school_total) * 100 : 0; ?><tr><td><strong><?= html_escape($row->division_name); ?></strong></td><td><span class="status-pill<?= (int) $row->record_count > 0 ? '' : ' muted'; ?>"><?= (int) $row->record_count > 0 ? 'Reporting' : 'No records'; ?></span></td><td><a href="<?= $record_link; ?>"><?= number_format((int) $row->school_count); ?> / <?= number_format($row_school_total); ?></a></td><td><?= number_format($row_submission_rate, 1); ?>%</td><td><a href="<?= $record_link; ?>"><?= number_format((int) $row->record_count); ?></a></td><td><a href="<?= $record_link; ?>"><?= number_format($row_assessed); ?></a></td><td><a href="<?= $record_link; ?>"><?= number_format((int) $row->learners_with_gap); ?></a></td><td><?= number_format($row_gap_rate, 1); ?>%</td></tr><?php endforeach; endif; ?></tbody></table></div></section>
    <?php else : ?><?php endif; ?>
</div>
