<style>
    .area-setup{--blue:#164b73;--line:#dce6ef}.area-setup .hero{margin:18px 0 22px;padding:28px;border-radius:16px;color:#fff;background:linear-gradient(120deg,#123d61,#2877a9)}.area-setup .hero h2{margin:0 0 7px;color:#fff}.area-setup .card{border:1px solid var(--line);border-radius:14px;box-shadow:0 5px 18px rgba(20,62,94,.05)}.area-setup .card-header{background:#f5faff;color:var(--blue);border-bottom:1px solid var(--line)}
</style>
<div class="area-setup">
    <div class="hero"><h2><i class="mdi mdi-tune mr-2"></i>Learning Area Setup</h2><p class="mb-0">Configure the learning areas available to school accounts in your division for each grade level.</p></div>
    <div class="card mb-4"><div class="card-header"><h4 class="mb-0">Select division</h4></div><div class="card-body"><form method="get" action="<?= base_url('Pages/learning_area_setup'); ?>"><div class="row align-items-end"><div class="col-md-8 form-group mb-md-0"><label for="division_id">Division</label><select id="division_id" name="division_id" class="custom-select" onchange="this.form.submit()"><?php foreach ($divisions as $division): ?><option value="<?= (int) $division->id; ?>" <?= (int) $selected_division_id === (int) $division->id ? 'selected' : ''; ?>><?= html_escape($division->description); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><button class="btn btn-outline-primary btn-block" type="submit">View division</button></div></div></form></div></div>
    <?php if ($this->session->flashdata('success')): ?><div class="alert alert-success"><?= $this->session->flashdata('success'); ?></div><?php endif; ?>
    <?php if ($this->session->flashdata('danger')): ?><div class="alert alert-danger"><?= $this->session->flashdata('danger'); ?></div><?php endif; ?>
    <div class="card mb-4"><div class="card-header"><h4 class="mb-0">Add learning area</h4></div><div class="card-body"><?= form_open('Pages/learning_area_setup_save'); ?><input type="hidden" name="division_id" value="<?= (int) $selected_division_id; ?>"><div class="row align-items-end"><div class="col-md-4 form-group mb-md-0"><label>Grade Level</label><select name="grade_level" class="custom-select" required><option value="">Select grade</option><?php foreach (array('Kindergarten','Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Grade 8','Grade 9','Grade 10','Grade 11','Grade 12') as $grade): ?><option><?= $grade; ?></option><?php endforeach; ?></select></div><div class="col-md-5 form-group mb-md-0"><label>Learning Area / Subject</label><input name="learning_area" class="form-control" placeholder="e.g. Mathematics" required></div><div class="col-md-3"><button class="btn btn-primary btn-block"><i class="mdi mdi-plus"></i> Add to setup</button></div></div><?= form_close(); ?></div></div>
    <div class="card"><div class="card-header"><h4 class="mb-0">Configured learning areas</h4></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Grade Level</th><th>Learning Area / Subject</th><th>Action</th></tr></thead><tbody><?php if (empty($areas)): ?><tr><td colspan="3" class="p-4 text-center text-muted">No learning areas set up yet. Add entries above to enable school data entry.</td></tr><?php else: foreach ($areas as $area): ?><tr><td><?= html_escape($area->grade_level); ?></td><td><?= html_escape($area->learning_area); ?></td><td><a href="<?= base_url('Pages/learning_competencies_view/' . (int) $area->id . '?division_id=' . (int) $selected_division_id); ?>" class="btn btn-sm btn-outline-secondary mr-1"><i class="mdi mdi-eye-outline"></i> View Competencies</a><a href="<?= base_url('Pages/learning_competency_setup/' . (int) $area->id . '?division_id=' . (int) $selected_division_id); ?>" class="btn btn-sm btn-outline-primary mr-1"><i class="mdi mdi-plus-box-outline"></i> Add Competencies</a><a href="<?= base_url('Pages/learning_area_setup_delete/' . (int) $area->id . '?division_id=' . (int) $selected_division_id); ?>" class="btn btn-sm btn-outline-danger" onclick="return confirm('Remove this learning area?');"><i class="mdi mdi-delete-outline"></i> Remove</a></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
</div>
